overrides: "pyexcel.yaml"
name: "{{project_name}}"
nick_name: "{{nickname}}"
version: "0.0.1"
current_version: "0.0.1"
release: "0.0.1"
{% if type == '2'%}
command_line_interface: "{{cli}}"
entry_point: "{{project | replace('-', '_')}}.main:main"
{% endif %}
dependencies: []
description: "{{description}}"