project: pyexcel
name: pyexcel
nick_name: pyexcel
copyright: copyright 2015-2019 Onni Software Ltd.
file_type: file type
author: C.W.
organisation: pyexcel
contact: wangc_2011@hotmail.com
license: New BSD
company: Onni Software Ltd.
branch: master
include_doctest: true
scm_host: github.com
extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.doctest'
  - 'sphinx.ext.intersphinx'
  - 'sphinx.ext.viewcode'
master: index
language: Python
lint_command: make lint
