name: pyexcel
nick_name: pyexcel
copyright_year: 2015-2018
file_type: file type
author: C.W.
organisation: pyexcel
contact: wangc_2011@hotmail.com
license: New BSD
company: Onni Software Ltd.
branch: master
include_doctest: true
